global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:

# rule_files:

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/prometheus"
    static_configs:
      - targets:
          ["shiba-metrics-alb-1560886969.ap-northeast-1.elb.amazonaws.com:9090"]
  - job_name: "nginx"
    metrics_path: "/nginx-exporter/metrics"
    scheme: http
    static_configs:
      - targets:
          ["shiba-metrics-alb-1560886969.ap-northeast-1.elb.amazonaws.com:9113"]
